import Button from "./Button";
import "../index.css";

const ButtonList = () => {
  const list = [
    "ALL",
    "Valorant",
    "Games",
    "NEWS",
    "BGMI",
    "Songs",
    "React",
    "Node",
    "Cooking",
    "Soccer",
    "Driving",
    "Watching",
    "Movies",
    "Music",
    "Travel",
    "Fitness",
    "Photography",
    "Art",
    "Design",
    "Programming",
    "Technology",
    "Science",
    "Books",
    "Food",
    "Health",
    "Fashion",
    "Sports",
    "Basketball",
    "Tennis",
    "Gaming",
    "Streaming",
    "Comedy",
    "Education",
    "Business",
    "Finance",
    "Investing",
    "Startups",
    "AI",
    "Machine Learning",
    "Data Science",
    "Cybersecurity",
    "Web Development",
    "Mobile Apps",
    "DIY",
    "Gardening",
    "Pets",
    "Nature",
    "Adventure",
    "Camping",
    "Hiking",
    "Yoga",
    "Meditation",
    "History",
    "Culture",
    "Politics",
    "Environment",
    "Space",
    "Astronomy",
    "Physics",
    "Chemistry",
    "Biology",
    "Mathematics",
    "Psychology",
    "Philosophy",
    "Writing",
    "Poetry",
    "Photography",
    "Filmmaking",
    "Acting",
    "Dancing",
    "Theater",
    "Gaming",
    "Esports",
    "Anime",
    "Manga",
    "Comics",
    "Cosplay",
    "Tech Reviews",
    "Unboxing",
    "Vlogging",
    "Podcasts",
    "Interviews",
    "Documentaries",
    "Tutorials",
    "How-To",
    "Life Hacks",
    "Productivity",
    "Time Management",
    "Motivation",
    "Self-Improvement",
    "Mindfulness",
    "Spirituality",
    "Religion",
    "Charity",
    "Volunteering",
    "Social Media",
    "Marketing",
    "Branding",
    "Content Creation",
    "Graphic Design",
    "UI/UX",
    "Animation",
    "3D Modeling",
    "Virtual Reality",
    "Augmented Reality",
    "Blockchain",
    "Cryptocurrency",
    "NFTs",
    "Gaming Consoles",
    "PC Building",
    "Smartphones",
    "Gadgets",
    "Home Automation",
    "Robotics",
    "Drones",
    "Electric Vehicles",
    "Renewable Energy",
    "Climate Change",
    "Conservation",
    "Wildlife",
    "Travel Vlogs",
    "Food Vlogs",
    "Fashion Vlogs",
    "Fitness Vlogs",
    "Tech Vlogs",
    "Car Reviews",
    "Bike Reviews",
    "Travel Guides",
    "Food Recipes",
    "Workout Plans",
    "Study Tips",
    "Career Advice",
    "Entrepreneurship",
    "Freelancing",
    "Remote Work",
    "Digital Nomad",
    "Language Learning",
    "Coding Challenges",
    "Game Development",
    "App Development",
    "Open Source",
    "DevOps",
    "Cloud Computing",
    "Networking",
    "Ethical Hacking",
    "Forensics",
    "Law",
  ];

  return (
    <div className="mx-4 bg-fixed p-4 w-[98%] flex gap-3 border bg-slate-300/30 overflow-x-auto whitespace-nowrap scrollbar-hide">
      {list.map((item, index) => {
        return <Button key={index} name={item} />;
      })}
    </div>
  );
};

export default ButtonList;
